development:
  adapter: postgresql
  encoding: unicode
  database: items_development
  pool: 5
  username: postgres
  password:

test:
  adapter: postgresql
  encoding: unicode
  database: items_test
  pool: 5
  username: postgres
  password:

production:
  adapter: postgresql
  encoding: unicode
  database: items_production
  pool: 5
  username: www-data
  password:
